In [1]:
import pandas as pd

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
data_to_load = "201908-citibike-tripdata.csv"
data_df = pd.read_csv(data_to_load)
data_df.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,2
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,1
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,1
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,2
5,632,2019-08-01 00:00:11.8060,2019-08-01 00:10:43.9590,173.0,Broadway & W 49 St,40.760683,-73.984527,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,21628,Subscriber,1998,1
6,117,2019-08-01 00:00:18.2010,2019-08-01 00:02:15.8600,3718.0,E 11 St & Avenue B,40.727464,-73.979504,326.0,E 11 St & 1 Ave,40.729538,-73.984267,25914,Subscriber,1995,1
7,378,2019-08-01 00:00:22.0840,2019-08-01 00:06:40.9350,493.0,W 45 St & 6 Ave,40.756800,-73.982912,3724.0,7 Ave & Central Park South,40.766741,-73.979069,34414,Subscriber,1999,1
8,1102,2019-08-01 00:00:22.0870,2019-08-01 00:18:44.3890,355.0,Bayard St & Baxter St,40.716021,-73.999744,3232.0,Bond St & Fulton St,40.689622,-73.983043,28226,Subscriber,1992,1
9,1733,2019-08-01 00:00:22.5580,2019-08-01 00:29:15.9080,513.0,W 56 St & 10 Ave,40.768254,-73.988639,469.0,Broadway & W 53 St,40.763441,-73.982681,33448,Customer,1968,1

In [3]:
# 2. Check the datatypes of your columns. 
data_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [13]:
# 3. Convert the 'tripduration' column to datetime datatype.
import datetime as dt
data_df['tripduration'] = pd.to_datetime(data_df['tripduration'], unit='s').apply(lambda x: x.strftime("%H:%M:%S"))

ValueError: non convertible value 1970-01-01 with the unit 's'

In [12]:
data_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1970-01-01,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2
1,1970-01-01,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,2
2,1970-01-01,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,1
3,1970-01-01,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,1
4,1970-01-01,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2344219,1970-01-01,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,1
2344220,1970-01-01,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,2
2344221,1970-01-01,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,0
2344222,1970-01-01,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,0
2344223,1970-01-01,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,1

In [10]:
# 4. Check the datatypes of your columns. 
data_df.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
dtype: object

In [7]:
# 5. Export the Dataframe as a new CSV file without the index.
data_df.to_csv('201908-citibike-tripdata_2.csv', index=False)